/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AdminUsoRouteImport } from './routes/admin.uso'
import { Route as AdminSuporteRouteImport } from './routes/admin.suporte'
import { Route as AdminPlanosRouteImport } from './routes/admin.planos'
import { Route as AdminMonitoramentoRouteImport } from './routes/admin.monitoramento'
import { Route as AdminModulosRouteImport } from './routes/admin.modulos'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminFlagsRouteImport } from './routes/admin.flags'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminClientesRouteImport } from './routes/admin.clientes'
import { Route as AdminAssinaturasRouteImport } from './routes/admin.assinaturas'
import { Route as AppSuporteRouteImport } from './routes/_app.suporte'
import { Route as AppSiteRouteImport } from './routes/_app.site'
import { Route as AppRelatoriosRouteImport } from './routes/_app.relatorios'
import { Route as AppPlanosRouteImport } from './routes/_app.planos'
import { Route as AppLeadsRouteImport } from './routes/_app.leads'
import { Route as AppIntegracoesRouteImport } from './routes/_app.integracoes'
import { Route as AppInsightsRouteImport } from './routes/_app.insights'
import { Route as AppConversoesRouteImport } from './routes/_app.conversoes'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'
import { Route as AppBlogRouteImport } from './routes/_app.blog'
import { Route as AppBibliotecaRouteImport } from './routes/_app.biblioteca'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AdminClientesIdRouteImport } from './routes/admin.clientes.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminUsoRoute = AdminUsoRouteImport.update({
  id: '/uso',
  path: '/uso',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSuporteRoute = AdminSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlanosRoute = AdminPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMonitoramentoRoute = AdminMonitoramentoRouteImport.update({
  id: '/monitoramento',
  path: '/monitoramento',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModulosRoute = AdminModulosRouteImport.update({
  id: '/modulos',
  path: '/modulos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFlagsRoute = AdminFlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssinaturasRoute = AdminAssinaturasRouteImport.update({
  id: '/assinaturas',
  path: '/assinaturas',
  getParentRoute: () => AdminRoute,
} as any)
const AppSuporteRoute = AppSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AppRoute,
} as any)
const AppSiteRoute = AppSiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanosRoute = AppPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegracoesRoute = AppIntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppConversoesRoute = AppConversoesRouteImport.update({
  id: '/conversoes',
  path: '/conversoes',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppBlogRoute = AppBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AppRoute,
} as any)
const AppBibliotecaRoute = AppBibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AdminClientesIdRoute = AdminClientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminClientesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/analytics': typeof AppAnalyticsRoute
  '/biblioteca': typeof AppBibliotecaRoute
  '/blog': typeof AppBlogRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/conversoes': typeof AppConversoesRoute
  '/insights': typeof AppInsightsRoute
  '/integracoes': typeof AppIntegracoesRoute
  '/leads': typeof AppLeadsRoute
  '/planos': typeof AppPlanosRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/site': typeof AppSiteRoute
  '/suporte': typeof AppSuporteRoute
  '/admin/assinaturas': typeof AdminAssinaturasRoute
  '/admin/clientes': typeof AdminClientesRouteWithChildren
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/flags': typeof AdminFlagsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/modulos': typeof AdminModulosRoute
  '/admin/monitoramento': typeof AdminMonitoramentoRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin/uso': typeof AdminUsoRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/clientes/$id': typeof AdminClientesIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/analytics': typeof AppAnalyticsRoute
  '/biblioteca': typeof AppBibliotecaRoute
  '/blog': typeof AppBlogRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/conversoes': typeof AppConversoesRoute
  '/insights': typeof AppInsightsRoute
  '/integracoes': typeof AppIntegracoesRoute
  '/leads': typeof AppLeadsRoute
  '/planos': typeof AppPlanosRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/site': typeof AppSiteRoute
  '/suporte': typeof AppSuporteRoute
  '/admin/assinaturas': typeof AdminAssinaturasRoute
  '/admin/clientes': typeof AdminClientesRouteWithChildren
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/flags': typeof AdminFlagsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/modulos': typeof AdminModulosRoute
  '/admin/monitoramento': typeof AdminMonitoramentoRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin/uso': typeof AdminUsoRoute
  '/': typeof AppIndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/clientes/$id': typeof AdminClientesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/biblioteca': typeof AppBibliotecaRoute
  '/_app/blog': typeof AppBlogRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/conversoes': typeof AppConversoesRoute
  '/_app/insights': typeof AppInsightsRoute
  '/_app/integracoes': typeof AppIntegracoesRoute
  '/_app/leads': typeof AppLeadsRoute
  '/_app/planos': typeof AppPlanosRoute
  '/_app/relatorios': typeof AppRelatoriosRoute
  '/_app/site': typeof AppSiteRoute
  '/_app/suporte': typeof AppSuporteRoute
  '/admin/assinaturas': typeof AdminAssinaturasRoute
  '/admin/clientes': typeof AdminClientesRouteWithChildren
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/flags': typeof AdminFlagsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/modulos': typeof AdminModulosRoute
  '/admin/monitoramento': typeof AdminMonitoramentoRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin/uso': typeof AdminUsoRoute
  '/_app/': typeof AppIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/clientes/$id': typeof AdminClientesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/analytics'
    | '/biblioteca'
    | '/blog'
    | '/configuracoes'
    | '/conversoes'
    | '/insights'
    | '/integracoes'
    | '/leads'
    | '/planos'
    | '/relatorios'
    | '/site'
    | '/suporte'
    | '/admin/assinaturas'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/flags'
    | '/admin/logs'
    | '/admin/modulos'
    | '/admin/monitoramento'
    | '/admin/planos'
    | '/admin/suporte'
    | '/admin/uso'
    | '/admin/'
    | '/admin/clientes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/analytics'
    | '/biblioteca'
    | '/blog'
    | '/configuracoes'
    | '/conversoes'
    | '/insights'
    | '/integracoes'
    | '/leads'
    | '/planos'
    | '/relatorios'
    | '/site'
    | '/suporte'
    | '/admin/assinaturas'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/flags'
    | '/admin/logs'
    | '/admin/modulos'
    | '/admin/monitoramento'
    | '/admin/planos'
    | '/admin/suporte'
    | '/admin/uso'
    | '/'
    | '/admin'
    | '/admin/clientes/$id'
  id:
    | '__root__'
    | '/_app'
    | '/admin'
    | '/auth'
    | '/_app/analytics'
    | '/_app/biblioteca'
    | '/_app/blog'
    | '/_app/configuracoes'
    | '/_app/conversoes'
    | '/_app/insights'
    | '/_app/integracoes'
    | '/_app/leads'
    | '/_app/planos'
    | '/_app/relatorios'
    | '/_app/site'
    | '/_app/suporte'
    | '/admin/assinaturas'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/flags'
    | '/admin/logs'
    | '/admin/modulos'
    | '/admin/monitoramento'
    | '/admin/planos'
    | '/admin/suporte'
    | '/admin/uso'
    | '/_app/'
    | '/admin/'
    | '/admin/clientes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/uso': {
      id: '/admin/uso'
      path: '/uso'
      fullPath: '/admin/uso'
      preLoaderRoute: typeof AdminUsoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/suporte': {
      id: '/admin/suporte'
      path: '/suporte'
      fullPath: '/admin/suporte'
      preLoaderRoute: typeof AdminSuporteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/planos': {
      id: '/admin/planos'
      path: '/planos'
      fullPath: '/admin/planos'
      preLoaderRoute: typeof AdminPlanosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/monitoramento': {
      id: '/admin/monitoramento'
      path: '/monitoramento'
      fullPath: '/admin/monitoramento'
      preLoaderRoute: typeof AdminMonitoramentoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/modulos': {
      id: '/admin/modulos'
      path: '/modulos'
      fullPath: '/admin/modulos'
      preLoaderRoute: typeof AdminModulosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/flags': {
      id: '/admin/flags'
      path: '/flags'
      fullPath: '/admin/flags'
      preLoaderRoute: typeof AdminFlagsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assinaturas': {
      id: '/admin/assinaturas'
      path: '/assinaturas'
      fullPath: '/admin/assinaturas'
      preLoaderRoute: typeof AdminAssinaturasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/suporte': {
      id: '/_app/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof AppSuporteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/site': {
      id: '/_app/site'
      path: '/site'
      fullPath: '/site'
      preLoaderRoute: typeof AppSiteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/planos': {
      id: '/_app/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof AppPlanosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integracoes': {
      id: '/_app/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof AppIntegracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insights': {
      id: '/_app/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/conversoes': {
      id: '/_app/conversoes'
      path: '/conversoes'
      fullPath: '/conversoes'
      preLoaderRoute: typeof AppConversoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/blog': {
      id: '/_app/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof AppBlogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/biblioteca': {
      id: '/_app/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof AppBibliotecaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/clientes/$id': {
      id: '/admin/clientes/$id'
      path: '/$id'
      fullPath: '/admin/clientes/$id'
      preLoaderRoute: typeof AdminClientesIdRouteImport
      parentRoute: typeof AdminClientesRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppBibliotecaRoute: typeof AppBibliotecaRoute
  AppBlogRoute: typeof AppBlogRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppConversoesRoute: typeof AppConversoesRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppIntegracoesRoute: typeof AppIntegracoesRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppPlanosRoute: typeof AppPlanosRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppSiteRoute: typeof AppSiteRoute
  AppSuporteRoute: typeof AppSuporteRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppBibliotecaRoute: AppBibliotecaRoute,
  AppBlogRoute: AppBlogRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppConversoesRoute: AppConversoesRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppIntegracoesRoute: AppIntegracoesRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppPlanosRoute: AppPlanosRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppSiteRoute: AppSiteRoute,
  AppSuporteRoute: AppSuporteRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminClientesRouteChildren {
  AdminClientesIdRoute: typeof AdminClientesIdRoute
}

const AdminClientesRouteChildren: AdminClientesRouteChildren = {
  AdminClientesIdRoute: AdminClientesIdRoute,
}

const AdminClientesRouteWithChildren = AdminClientesRoute._addFileChildren(
  AdminClientesRouteChildren,
)

interface AdminRouteChildren {
  AdminAssinaturasRoute: typeof AdminAssinaturasRoute
  AdminClientesRoute: typeof AdminClientesRouteWithChildren
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminFlagsRoute: typeof AdminFlagsRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminModulosRoute: typeof AdminModulosRoute
  AdminMonitoramentoRoute: typeof AdminMonitoramentoRoute
  AdminPlanosRoute: typeof AdminPlanosRoute
  AdminSuporteRoute: typeof AdminSuporteRoute
  AdminUsoRoute: typeof AdminUsoRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAssinaturasRoute: AdminAssinaturasRoute,
  AdminClientesRoute: AdminClientesRouteWithChildren,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminFlagsRoute: AdminFlagsRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminModulosRoute: AdminModulosRoute,
  AdminMonitoramentoRoute: AdminMonitoramentoRoute,
  AdminPlanosRoute: AdminPlanosRoute,
  AdminSuporteRoute: AdminSuporteRoute,
  AdminUsoRoute: AdminUsoRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
